-- ============================================================================
-- HR module RLS policies (multi-tenant isolation)
-- ============================================================================
-- This block is appended manually to the migration SQL generated by
-- `prisma migrate dev --create-only --name hr_module_foundation`.
--
-- App must SET LOCAL app.account_id = '<uuid>' via Prisma middleware before
-- every query (see packages/db/src/account-context.ts pattern used by mavjud
-- modules).
-- ============================================================================

-- 1. Partial unique index on Employee.username — only enforced when NOT NULL.
--    Prisma generates a plain UNIQUE index from @@unique([accountId, username]);
--    we replace it with a partial index so NULL usernames don't collide.
DROP INDEX IF EXISTS "Employee_account_username_uk";
CREATE UNIQUE INDEX "Employee_account_username_uk"
  ON "Employee"("account_id", "username")
  WHERE "username" IS NOT NULL;

-- 2. Enable RLS + tenant_isolation policy for each new HR table.
--    Policy: row visible iff account_id matches current session setting.
DO $$
DECLARE
  tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'hr_task_template',
    'hr_task_log',
    'hr_attendance',
    'hr_telegram_account',
    'hr_telegram_session',
    'hr_chat_history',
    'hr_telegram_outbox',
    'hr_bonus_fine_log',
    'hr_bonus_fine_rule',
    'hr_salary_config',
    'hr_kpi_daily_log',
    'hr_kpi_monthly_score',
    'hr_employee_permission',
    'hr_role',
    'hr_notification_template',
    'hr_activity_log'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING ("account_id" = current_setting(''app.account_id'', true)::uuid)',
      tbl
    );
  END LOOP;
END $$;
