-- AlterTable
ALTER TABLE "enters" ADD COLUMN     "currency" VARCHAR(3) NOT NULL DEFAULT 'UZS',
ADD COLUMN     "rate_value" BIGINT NOT NULL DEFAULT 100000000;

-- AlterTable
ALTER TABLE "losses" ADD COLUMN     "currency" VARCHAR(3) NOT NULL DEFAULT 'UZS',
ADD COLUMN     "rate_value" BIGINT NOT NULL DEFAULT 100000000;

-- AlterTable
ALTER TABLE "moves" ADD COLUMN     "currency" VARCHAR(3) NOT NULL DEFAULT 'UZS',
ADD COLUMN     "rate_value" BIGINT NOT NULL DEFAULT 100000000;
